#!/usr/bin/env python3
"""Generate missing player entries for every team/decade/position gap."""
import json, hashlib

GAPS = [
"ARI|80s|K","ARI|80s|DB","ARI|90s|RB","ARI|90s|WR","ARI|90s|K","ARI|90s|LB",
"ARI|00s|RB","ARI|00s|EDGE","ARI|10s|QB","ARI|10s|DB",
"ARI|20s|WR","ARI|20s|EDGE","ARI|20s|LB",
"ATL|70s|WR","ATL|70s|K","ATL|70s|DB",
"ATL|80s|QB","ATL|80s|K","ATL|80s|EDGE","ATL|80s|LB",
"ATL|90s|QB","ATL|90s|WR","ATL|00s|K","ATL|00s|DB",
"ATL|10s|RB","ATL|10s|EDGE","ATL|20s|QB","ATL|20s|DB",
"BAL|00s|QB","BAL|10s|RB","BAL|10s|WR","BAL|20s|EDGE",
"BUF|60s|QB","BUF|60s|RB","BUF|60s|WR","BUF|60s|K","BUF|60s|EDGE","BUF|60s|DB",
"BUF|70s|WR","BUF|70s|K","BUF|70s|EDGE","BUF|70s|LB",
"BUF|90s|DB","BUF|00s|QB","BUF|00s|RB","BUF|00s|WR","BUF|00s|EDGE","BUF|00s|DB",
"BUF|20s|RB",
"CAR|90s|QB","CAR|90s|RB","CAR|90s|WR","CAR|90s|K","CAR|90s|EDGE","CAR|90s|DB",
"CAR|00s|LB","CAR|10s|WR","CAR|10s|K","CAR|20s|QB","CAR|20s|RB","CAR|20s|WR",
"CAR|20s|EDGE","CAR|20s|LB",
"CHI|60s|QB","CHI|60s|K","CHI|60s|DB",
"CHI|70s|QB","CHI|70s|WR","CHI|70s|K","CHI|70s|DB",
"CHI|80s|WR","CHI|80s|DB",
"CHI|00s|QB","CHI|00s|RB","CHI|10s|RB","CHI|10s|K","CHI|10s|LB","CHI|10s|DB",
"CHI|20s|RB","CHI|20s|WR","CHI|20s|LB",
"CIN|80s|WR","CIN|80s|EDGE","CIN|80s|LB","CIN|80s|DB",
"CIN|90s|K","CIN|90s|EDGE","CIN|90s|LB","CIN|90s|DB",
"CIN|00s|EDGE","CIN|00s|LB","CIN|00s|DB",
"CIN|10s|RB","CIN|10s|WR","CIN|10s|K","CIN|10s|DB",
"CIN|20s|LB",
"CLE|60s|WR","CLE|60s|EDGE","CLE|60s|LB","CLE|60s|DB",
"CLE|70s|QB","CLE|70s|RB","CLE|70s|WR","CLE|70s|EDGE","CLE|70s|LB","CLE|70s|DB",
"CLE|80s|RB","CLE|80s|K","CLE|80s|LB",
"CLE|00s|QB","CLE|00s|RB","CLE|00s|WR","CLE|00s|EDGE","CLE|00s|LB","CLE|00s|DB",
"CLE|10s|QB","CLE|10s|RB","CLE|10s|WR","CLE|10s|K","CLE|10s|EDGE","CLE|10s|DB",
"CLE|20s|QB","CLE|20s|WR","CLE|20s|K",
"DAL|60s|RB","DAL|60s|K","DAL|60s|DB",
"DAL|70s|RB","DAL|80s|WR",
"DAL|90s|K","DAL|90s|EDGE","DAL|90s|LB",
"DAL|00s|RB","DAL|00s|K","DAL|00s|LB","DAL|00s|DB",
"DAL|10s|K","DAL|10s|EDGE","DAL|10s|DB",
"DAL|20s|RB","DAL|20s|LB",
"DEN|60s|QB","DEN|60s|RB","DEN|60s|WR","DEN|60s|K","DEN|60s|EDGE","DEN|60s|DB",
"DEN|70s|WR","DEN|70s|K",
"DEN|80s|WR","DEN|80s|K",
"DEN|90s|EDGE","DEN|90s|LB",
"DEN|00s|QB","DEN|10s|RB","DEN|10s|LB","DEN|10s|DB",
"DEN|20s|QB","DEN|20s|WR","DEN|20s|K","DEN|20s|LB",
"DET|60s|QB","DET|60s|RB","DET|60s|WR","DET|60s|K",
"DET|80s|WR","DET|80s|EDGE","DET|80s|LB","DET|80s|DB",
"DET|90s|QB","DET|90s|DB",
"DET|00s|QB","DET|00s|RB","DET|00s|LB","DET|00s|DB",
"DET|10s|RB","DET|10s|K","DET|10s|LB","DET|10s|DB",
"DET|20s|K","DET|20s|LB","DET|20s|DB",
"GB|60s|WR","GB|60s|K","GB|60s|DB",
"GB|90s|RB","GB|90s|K","GB|90s|LB","GB|90s|DB",
"GB|00s|QB","GB|00s|K","GB|00s|EDGE","GB|00s|LB",
"GB|10s|WR","GB|10s|DB",
"GB|20s|RB","GB|20s|EDGE",
"HOU|00s|QB","HOU|00s|RB","HOU|00s|K",
"HOU|10s|K","HOU|10s|DB",
"HOU|20s|RB","HOU|20s|LB","HOU|20s|DB",
"IND|60s|K","IND|60s|EDGE","IND|60s|LB","IND|60s|DB",
"IND|80s|QB","IND|80s|WR","IND|80s|LB",
"IND|00s|LB","IND|10s|RB","IND|10s|LB","IND|10s|DB",
"IND|20s|QB","IND|20s|WR",
"JAX|90s|EDGE","JAX|90s|LB","JAX|90s|DB",
"JAX|00s|QB","JAX|00s|K","JAX|00s|EDGE","JAX|00s|LB",
"JAX|10s|QB","JAX|10s|RB","JAX|10s|WR","JAX|10s|K","JAX|10s|EDGE",
"JAX|20s|RB","JAX|20s|LB",
"KC|60s|RB","KC|60s|K","KC|60s|DB",
"KC|70s|QB","KC|70s|WR",
"KC|80s|QB","KC|80s|RB","KC|80s|WR","KC|80s|EDGE","KC|80s|LB","KC|80s|DB",
"KC|90s|QB","KC|90s|WR","KC|90s|LB",
"KC|00s|K","KC|00s|EDGE","KC|00s|DB",
"KC|10s|QB","KC|10s|EDGE","KC|10s|DB",
"KC|20s|LB",
"LV|70s|RB","LV|70s|EDGE",
"LV|80s|QB","LV|80s|WR","LV|80s|DB",
"LV|90s|RB","LV|90s|EDGE","LV|90s|LB",
"LV|00s|RB","LV|00s|EDGE","LV|00s|LB",
"LV|10s|RB","LV|10s|LB","LV|10s|DB",
"LV|20s|QB","LV|20s|LB","LV|20s|DB",
"LAC|60s|K","LAC|60s|EDGE","LAC|60s|LB","LAC|60s|DB",
"LAC|80s|RB","LAC|80s|K","LAC|80s|EDGE","LAC|80s|LB",
"LAC|90s|QB","LAC|90s|WR","LAC|90s|DB",
"LAC|00s|K","LAC|00s|EDGE","LAC|00s|DB",
"LAC|10s|K","LAC|10s|EDGE","LAC|10s|LB","LAC|10s|DB",
"LAC|20s|RB","LAC|20s|WR","LAC|20s|K","LAC|20s|LB",
"LAR|60s|QB","LAR|60s|RB","LAR|60s|WR","LAR|60s|K",
"LAR|70s|QB","LAR|70s|WR","LAR|70s|K","LAR|70s|DB",
"LAR|80s|K","LAR|80s|EDGE",
"LAR|00s|EDGE","LAR|00s|LB","LAR|00s|DB",
"LAR|10s|RB","LAR|10s|LB","LAR|10s|DB",
"LAR|20s|RB","LAR|20s|LB",
"MIA|70s|EDGE","MIA|70s|DB",
"MIA|80s|K","MIA|80s|EDGE","MIA|80s|DB",
"MIA|90s|RB","MIA|90s|DB",
"MIA|00s|QB","MIA|00s|RB","MIA|00s|WR",
"MIA|20s|RB","MIA|20s|K","MIA|20s|EDGE","MIA|20s|LB",
"MIN|70s|WR",
"MIN|80s|QB","MIN|80s|RB","MIN|80s|WR","MIN|80s|EDGE","MIN|80s|LB","MIN|80s|DB",
"MIN|90s|QB","MIN|90s|LB","MIN|90s|DB",
"MIN|00s|EDGE","MIN|00s|LB","MIN|00s|DB",
"MIN|10s|QB","MIN|10s|WR","MIN|10s|K",
"MIN|20s|RB","MIN|20s|K","MIN|20s|EDGE","MIN|20s|LB","MIN|20s|DB",
"NE|60s|QB","NE|60s|RB","NE|60s|WR","NE|60s|EDGE","NE|60s|DB",
"NE|80s|QB","NE|80s|WR",
"NE|90s|WR","NE|90s|K","NE|90s|EDGE","NE|90s|LB",
"NE|00s|LB","NE|10s|RB","NE|10s|EDGE",
"NE|20s|QB","NE|20s|WR","NE|20s|LB","NE|20s|DB",
"NO|70s|WR","NO|70s|LB","NO|70s|DB",
"NO|80s|RB","NO|80s|WR","NO|80s|DB",
"NO|90s|RB","NO|90s|WR","NO|90s|DB",
"NO|00s|K","NO|00s|EDGE","NO|00s|LB","NO|00s|DB",
"NO|10s|RB","NO|10s|DB",
"NO|20s|QB",
"NYG|60s|K","NYG|60s|EDGE",
"NYG|70s|QB","NYG|70s|RB","NYG|70s|WR","NYG|70s|K","NYG|70s|EDGE","NYG|70s|DB",
"NYG|80s|RB",
"NYG|90s|QB","NYG|90s|RB","NYG|90s|WR","NYG|90s|K","NYG|90s|EDGE","NYG|90s|LB",
"NYG|00s|QB","NYG|00s|WR","NYG|00s|LB",
"NYG|10s|RB","NYG|10s|K","NYG|10s|EDGE","NYG|10s|LB","NYG|10s|DB",
"NYG|20s|QB","NYG|20s|WR","NYG|20s|LB",
"NYJ|60s|K","NYJ|60s|EDGE","NYJ|60s|DB",
"NYJ|70s|QB","NYJ|70s|RB","NYJ|70s|WR","NYJ|70s|EDGE","NYJ|70s|LB","NYJ|70s|DB",
"NYJ|80s|WR","NYJ|80s|LB","NYJ|80s|DB",
"NYJ|90s|QB","NYJ|90s|RB","NYJ|90s|K","NYJ|90s|LB","NYJ|90s|DB",
"NYJ|00s|QB","NYJ|00s|DB",
"NYJ|10s|QB","NYJ|10s|RB","NYJ|10s|WR","NYJ|10s|K","NYJ|10s|LB",
"NYJ|20s|QB","NYJ|20s|K",
"PHI|60s|QB","PHI|60s|RB","PHI|60s|K","PHI|60s|DB",
"PHI|70s|QB","PHI|70s|RB","PHI|70s|WR","PHI|70s|K","PHI|70s|EDGE","PHI|70s|DB",
"PHI|80s|RB","PHI|80s|LB","PHI|80s|DB",
"PHI|90s|RB","PHI|90s|WR","PHI|90s|K",
"PHI|00s|RB","PHI|00s|EDGE",
"PHI|10s|LB","PHI|10s|DB",
"PHI|20s|LB",
"PIT|80s|QB","PIT|80s|RB","PIT|80s|EDGE",
"PIT|90s|WR","PIT|00s|RB","PIT|00s|K","PIT|00s|LB",
"PIT|10s|EDGE","PIT|10s|DB",
"PIT|20s|QB","PIT|20s|LB",
"SF|80s|K","SF|80s|LB",
"SF|90s|RB","SF|90s|LB","SF|90s|DB",
"SF|00s|QB","SF|00s|LB","SF|00s|DB",
"SF|10s|RB","SF|10s|WR","SF|10s|DB",
"SF|20s|K","SF|20s|DB",
"SEA|80s|QB","SEA|80s|EDGE",
"SEA|90s|WR","SEA|90s|K","SEA|90s|LB","SEA|90s|DB",
"SEA|00s|WR","SEA|00s|EDGE","SEA|00s|DB",
"SEA|10s|WR","SEA|20s|EDGE",
"TB|80s|WR","TB|80s|LB","TB|80s|DB",
"TB|90s|QB","TB|90s|RB","TB|90s|WR","TB|90s|EDGE","TB|90s|DB",
"TB|00s|QB","TB|00s|WR",
"TB|10s|QB","TB|10s|RB","TB|10s|DB",
"TEN|70s|QB","TEN|70s|RB","TEN|70s|WR","TEN|70s|K","TEN|70s|EDGE","TEN|70s|DB",
"TEN|80s|WR","TEN|80s|K","TEN|80s|EDGE","TEN|80s|DB",
"TEN|90s|WR","TEN|90s|EDGE","TEN|90s|LB","TEN|90s|DB",
"TEN|00s|WR","TEN|00s|LB","TEN|00s|DB",
"TEN|10s|RB","TEN|10s|WR","TEN|10s|K","TEN|10s|LB",
"TEN|20s|K","TEN|20s|LB","TEN|20s|DB",
"WAS|60s|RB","WAS|60s|K","WAS|60s|LB","WAS|60s|DB",
"WAS|70s|QB","WAS|70s|K","WAS|70s|DB",
"WAS|80s|EDGE","WAS|80s|LB",
"WAS|90s|QB","WAS|90s|WR","WAS|90s|K",
"WAS|00s|QB","WAS|00s|K","WAS|00s|EDGE",
"WAS|10s|QB","WAS|10s|RB","WAS|10s|DB",
"WAS|20s|RB","WAS|20s|LB","WAS|20s|DB",
]

# Real player names mapped to gaps
KNOWN = {
# ARI
"ARI|80s|K":"Al Del Greco","ARI|80s|DB":"Lionel Washington",
"ARI|90s|RB":"Garrison Hearst","ARI|90s|WR":"Rob Moore","ARI|90s|K":"Greg Davis","ARI|90s|LB":"Eric Hill",
"ARI|00s|RB":"Marcel Shipp","ARI|00s|EDGE":"Bertrand Berry",
"ARI|10s|QB":"Carson Palmer","ARI|10s|DB":"Patrick Peterson",
"ARI|20s|WR":"DeAndre Hopkins","ARI|20s|EDGE":"Chandler Jones","ARI|20s|LB":"Isaiah Simmons",
# ATL
"ATL|70s|WR":"Alfred Jenkins","ATL|70s|K":"Tim Mazzetti","ATL|70s|DB":"Rolland Lawrence",
"ATL|80s|QB":"Steve Bartkowski","ATL|80s|K":"Mick Luckhurst","ATL|80s|EDGE":"Rick Bryan","ATL|80s|LB":"Buddy Curry",
"ATL|90s|QB":"Chris Chandler","ATL|90s|WR":"Terance Mathis",
"ATL|00s|K":"Jay Feely","ATL|00s|DB":"DeAngelo Hall",
"ATL|10s|RB":"Devonta Freeman","ATL|10s|EDGE":"Vic Beasley",
"ATL|20s|QB":"Marcus Mariota","ATL|20s|DB":"A.J. Terrell",
# BAL
"BAL|00s|QB":"Kyle Boller","BAL|10s|RB":"Justin Forsett","BAL|10s|WR":"Steve Smith Sr.",
"BAL|20s|EDGE":"Odafe Oweh",
# BUF
"BUF|60s|QB":"Jack Kemp","BUF|60s|RB":"Cookie Gilchrist","BUF|60s|WR":"Elbert Dubenion","BUF|60s|K":"Pete Gogolak","BUF|60s|EDGE":"Tom Sestak","BUF|60s|DB":"Butch Byrd",
"BUF|70s|WR":"J.D. Hill","BUF|70s|K":"John Leypoldt","BUF|70s|EDGE":"Sherman White","BUF|70s|LB":"Jim Haslett",
"BUF|90s|DB":"Henry Jones",
"BUF|00s|QB":"Drew Bledsoe","BUF|00s|RB":"Travis Henry","BUF|00s|WR":"Eric Moulds","BUF|00s|EDGE":"Aaron Schobel","BUF|00s|DB":"Nate Clements",
"BUF|20s|RB":"James Cook",
# CAR
"CAR|90s|QB":"Kerry Collins","CAR|90s|RB":"Tim Biakabutuka","CAR|90s|WR":"Muhsin Muhammad","CAR|90s|K":"John Kasay","CAR|90s|EDGE":"Kevin Greene","CAR|90s|DB":"Eric Davis",
"CAR|00s|LB":"Dan Morgan","CAR|10s|WR":"Kelvin Benjamin","CAR|10s|K":"Graham Gano",
"CAR|20s|QB":"Bryce Young","CAR|20s|RB":"Miles Sanders","CAR|20s|WR":"Adam Thielen","CAR|20s|EDGE":"Brian Burns","CAR|20s|LB":"Shaq Thompson",
# CHI
"CHI|60s|QB":"Billy Wade","CHI|60s|K":"Roger Leclerc","CHI|60s|DB":"Richie Petitbon",
"CHI|70s|QB":"Bobby Douglass","CHI|70s|WR":"James Scott","CHI|70s|K":"Bob Thomas","CHI|70s|DB":"Gary Fencik",
"CHI|80s|WR":"Willie Gault","CHI|80s|DB":"Dave Duerson",
"CHI|00s|QB":"Rex Grossman","CHI|00s|RB":"Thomas Jones",
"CHI|10s|RB":"Jordan Howard","CHI|10s|K":"Robbie Gould","CHI|10s|LB":"Danny Trevathan","CHI|10s|DB":"Kyle Fuller",
"CHI|20s|RB":"Khalil Herbert","CHI|20s|WR":"DJ Moore","CHI|20s|LB":"Tremaine Edmunds",
# CIN
"CIN|80s|WR":"Cris Collinsworth","CIN|80s|EDGE":"Eddie Edwards","CIN|80s|LB":"Reggie Williams","CIN|80s|DB":"Ken Riley",
"CIN|90s|K":"Doug Pelfrey","CIN|90s|EDGE":"Alfred Williams","CIN|90s|LB":"James Francis","CIN|90s|DB":"Ashley Ambrose",
"CIN|00s|EDGE":"Justin Smith","CIN|00s|LB":"Takeo Spikes","CIN|00s|DB":"Tory James",
"CIN|10s|RB":"Giovani Bernard","CIN|10s|WR":"A.J. Green","CIN|10s|K":"Mike Nugent","CIN|10s|DB":"Dre Kirkpatrick",
"CIN|20s|LB":"Logan Wilson",
# CLE
"CLE|60s|WR":"Gary Collins","CLE|60s|EDGE":"Bill Glass","CLE|60s|LB":"Jim Houston","CLE|60s|DB":"Larry Wilson",
"CLE|70s|QB":"Mike Phipps","CLE|70s|RB":"Greg Pruitt","CLE|70s|WR":"Reggie Rucker","CLE|70s|EDGE":"Jerry Sherk","CLE|70s|LB":"Bob Babich","CLE|70s|DB":"Thom Darden",
"CLE|80s|RB":"Kevin Mack","CLE|80s|K":"Matt Bahr","CLE|80s|LB":"Clay Matthews Jr.",
"CLE|00s|QB":"Tim Couch","CLE|00s|RB":"William Green","CLE|00s|WR":"Dennis Northcutt","CLE|00s|EDGE":"Courtney Brown","CLE|00s|LB":"Andra Davis","CLE|00s|DB":"Daylon McCutcheon",
"CLE|10s|QB":"Baker Mayfield","CLE|10s|RB":"Duke Johnson","CLE|10s|WR":"Jarvis Landry","CLE|10s|K":"Phil Dawson","CLE|10s|EDGE":"Emmanuel Ogbah","CLE|10s|DB":"Denzel Ward",
"CLE|20s|QB":"Deshaun Watson","CLE|20s|WR":"Amari Cooper","CLE|20s|K":"Dustin Hopkins",
# DAL
"DAL|60s|RB":"Don Perkins","DAL|60s|K":"Danny Villanueva","DAL|60s|DB":"Mel Renfro",
"DAL|70s|RB":"Robert Newhouse","DAL|80s|WR":"Drew Pearson",
"DAL|90s|K":"Chris Boniol","DAL|90s|EDGE":"Charles Haley","DAL|90s|LB":"Darrin Smith",
"DAL|00s|RB":"Julius Jones","DAL|00s|K":"Billy Cundiff","DAL|00s|LB":"Bradie James","DAL|00s|DB":"Terence Newman",
"DAL|10s|K":"Dan Bailey","DAL|10s|EDGE":"DeMarcus Lawrence","DAL|10s|DB":"Byron Jones",
"DAL|20s|RB":"Tony Pollard","DAL|20s|LB":"Leighton Vander Esch",
# DEN
"DEN|60s|QB":"Frank Tripucka","DEN|60s|RB":"Cookie Gilchrist","DEN|60s|WR":"Lionel Taylor","DEN|60s|K":"Gene Mingo","DEN|60s|EDGE":"Rich Jackson","DEN|60s|DB":"Goose Gonsoulin",
"DEN|70s|WR":"Haven Moses","DEN|70s|K":"Jim Turner",
"DEN|80s|WR":"Vance Johnson","DEN|80s|K":"Rich Karlis",
"DEN|90s|EDGE":"Neil Smith","DEN|90s|LB":"Bill Romanowski",
"DEN|00s|QB":"Jake Plummer","DEN|10s|RB":"C.J. Anderson","DEN|10s|LB":"Brandon Marshall","DEN|10s|DB":"Chris Harris Jr.",
"DEN|20s|QB":"Russell Wilson","DEN|20s|WR":"Jerry Jeudy","DEN|20s|K":"Brandon McManus","DEN|20s|LB":"Josey Jewell",
# DET
"DET|60s|QB":"Milt Plum","DET|60s|RB":"Nick Pietrosante","DET|60s|WR":"Gail Cogdill","DET|60s|K":"Wayne Walker",
"DET|80s|WR":"Leonard Thompson","DET|80s|EDGE":"Al Baker","DET|80s|LB":"Ken Fantetti","DET|80s|DB":"Bobby Watkins",
"DET|90s|QB":"Scott Mitchell","DET|90s|DB":"Robert Bailey",
"DET|00s|QB":"Joey Harrington","DET|00s|RB":"Kevin Jones","DET|00s|LB":"Boss Bailey","DET|00s|DB":"Dre Bly",
"DET|10s|RB":"Theo Riddick","DET|10s|K":"Matt Prater","DET|10s|LB":"Tahir Whitehead","DET|10s|DB":"Darius Slay",
"DET|20s|K":"Michael Badgley","DET|20s|LB":"Alex Anzalone","DET|20s|DB":"Kerby Joseph",
# GB
"GB|60s|WR":"Boyd Dowler","GB|60s|K":"Don Chandler","GB|60s|DB":"Herb Adderley",
"GB|90s|RB":"Edgar Bennett","GB|90s|K":"Chris Jacke","GB|90s|LB":"George Koonce","GB|90s|DB":"LeRoy Butler",
"GB|00s|QB":"Brett Favre","GB|00s|K":"Ryan Longwell","GB|00s|EDGE":"Kabeer Gbaja-Biamila","GB|00s|LB":"Nick Barnett",
"GB|10s|WR":"Jordy Nelson","GB|10s|DB":"Ha Ha Clinton-Dix",
"GB|20s|RB":"AJ Dillon","GB|20s|EDGE":"Rashan Gary",
# HOU
"HOU|00s|QB":"David Carr","HOU|00s|RB":"Domanick Williams","HOU|00s|K":"Kris Brown",
"HOU|10s|K":"Ka'imi Fairbairn","HOU|10s|DB":"Johnathan Joseph",
"HOU|20s|RB":"Dameon Pierce","HOU|20s|LB":"Christian Harris","HOU|20s|DB":"Derek Stingley Jr.",
# IND
"IND|60s|K":"Lou Michaels","IND|60s|EDGE":"Gino Marchetti","IND|60s|LB":"Don Shinnick","IND|60s|DB":"Bobby Boyd",
"IND|80s|QB":"Gary Hogeboom","IND|80s|WR":"Bill Brooks","IND|80s|LB":"Duane Bickett",
"IND|00s|LB":"Cato June","IND|10s|RB":"Frank Gore","IND|10s|LB":"Darius Leonard","IND|10s|DB":"Kenny Moore II",
"IND|20s|QB":"Anthony Richardson","IND|20s|WR":"Michael Pittman Jr.",
# JAX
"JAX|90s|EDGE":"Tony Brackens","JAX|90s|LB":"Kevin Hardy","JAX|90s|DB":"Aaron Beasley",
"JAX|00s|QB":"David Garrard","JAX|00s|K":"Josh Scobee","JAX|00s|EDGE":"Bobby McCray","JAX|00s|LB":"Mike Peterson",
"JAX|10s|QB":"Blake Bortles","JAX|10s|RB":"Leonard Fournette","JAX|10s|WR":"Allen Robinson","JAX|10s|K":"Josh Lambo","JAX|10s|EDGE":"Yannick Ngakoue",
"JAX|20s|RB":"Travis Etienne","JAX|20s|LB":"Foyesade Oluokun",
# KC
"KC|60s|RB":"Mike Garrett","KC|60s|K":"Jan Stenerud","KC|60s|DB":"Johnny Robinson",
"KC|70s|QB":"Mike Livingston","KC|70s|WR":"Otis Taylor",
"KC|80s|QB":"Bill Kenney","KC|80s|RB":"Joe Delaney","KC|80s|WR":"Stephone Paige","KC|80s|EDGE":"Art Still","KC|80s|LB":"Gary Spani","KC|80s|DB":"Albert Lewis",
"KC|90s|QB":"Steve Bono","KC|90s|WR":"J.J. Birden","KC|90s|LB":"Derrick Thomas",
"KC|00s|K":"Lawrence Tynes","KC|00s|EDGE":"Jared Allen","KC|00s|DB":"Greg Wesley",
"KC|10s|QB":"Alex Smith","KC|10s|EDGE":"Justin Houston","KC|10s|DB":"Eric Berry",
"KC|20s|LB":"Nick Bolton",
# LV
"LV|70s|RB":"Clarence Davis","LV|70s|EDGE":"Otis Sistrunk",
"LV|80s|QB":"Jim Plunkett","LV|80s|WR":"Cliff Branch","LV|80s|DB":"Lester Hayes",
"LV|90s|RB":"Harvey Williams","LV|90s|EDGE":"Anthony Smith","LV|90s|LB":"Greg Biekert",
"LV|00s|RB":"Charlie Garner","LV|00s|EDGE":"Derrick Burgess","LV|00s|LB":"Napoleon Harris",
"LV|10s|RB":"Latavius Murray","LV|10s|LB":"NaVorro Bowman","LV|10s|DB":"Charles Woodson",
"LV|20s|QB":"Aidan O'Connell","LV|20s|LB":"Robert Spillane","LV|20s|DB":"Nate Hobbs",
# LAC
"LAC|60s|K":"George Blair","LAC|60s|EDGE":"Earl Faison","LAC|60s|LB":"Frank Buncom","LAC|60s|DB":"Dick Westmoreland",
"LAC|80s|RB":"Gary Anderson","LAC|80s|K":"Rolf Benirschke","LAC|80s|EDGE":"Fred Dean","LAC|80s|LB":"Chip Banks",
"LAC|90s|QB":"Stan Humphries","LAC|90s|WR":"Anthony Miller","LAC|90s|DB":"Stanley Richard",
"LAC|00s|K":"Nate Kaeding","LAC|00s|EDGE":"Shaun Phillips","LAC|00s|DB":"Quentin Jammer",
"LAC|10s|K":"Nick Novak","LAC|10s|EDGE":"Melvin Ingram","LAC|10s|LB":"Denzel Perryman","LAC|10s|DB":"Casey Hayward",
"LAC|20s|RB":"Austin Ekeler","LAC|20s|WR":"Keenan Allen","LAC|20s|K":"Cameron Dicker","LAC|20s|LB":"Kenneth Murray",
# LAR
"LAR|60s|QB":"Roman Gabriel","LAR|60s|RB":"Dick Bass","LAR|60s|WR":"Jack Snow","LAR|60s|K":"Bruce Gossett",
"LAR|70s|QB":"James Harris","LAR|70s|WR":"Harold Jackson","LAR|70s|K":"Tom Dempsey","LAR|70s|DB":"Monte Jackson",
"LAR|80s|K":"Mike Lansford","LAR|80s|EDGE":"Gary Jeter",
"LAR|00s|EDGE":"Leonard Little","LAR|00s|LB":"London Fletcher","LAR|00s|DB":"Aeneas Williams",
"LAR|10s|RB":"Todd Gurley","LAR|10s|LB":"Cory Littleton","LAR|10s|DB":"Marcus Peters",
"LAR|20s|RB":"Cam Akers","LAR|20s|LB":"Ernest Jones",
# MIA
"MIA|70s|EDGE":"Vern Den Herder","MIA|70s|DB":"Dick Anderson",
"MIA|80s|K":"Fuad Reveiz","MIA|80s|EDGE":"Doug Betters","MIA|80s|DB":"William Judson",
"MIA|90s|RB":"Karim Abdul-Jabbar","MIA|90s|DB":"Troy Vincent",
"MIA|00s|QB":"Jay Fiedler","MIA|00s|RB":"Ricky Williams","MIA|00s|WR":"Chris Chambers",
"MIA|20s|RB":"Raheem Mostert","MIA|20s|K":"Jason Sanders","MIA|20s|EDGE":"Jaelan Phillips","MIA|20s|LB":"Jerome Baker",
# MIN
"MIN|70s|WR":"John Gilliam",
"MIN|80s|QB":"Tommy Kramer","MIN|80s|RB":"Darrin Nelson","MIN|80s|WR":"Anthony Carter","MIN|80s|EDGE":"Chris Doleman","MIN|80s|LB":"Scott Studwell","MIN|80s|DB":"Joey Browner",
"MIN|90s|QB":"Warren Moon","MIN|90s|LB":"Jack Del Rio","MIN|90s|DB":"Robert Griffith",
"MIN|00s|EDGE":"Kevin Williams","MIN|00s|LB":"E.J. Henderson","MIN|00s|DB":"Antoine Winfield",
"MIN|10s|QB":"Teddy Bridgewater","MIN|10s|WR":"Adam Thielen","MIN|10s|K":"Blair Walsh",
"MIN|20s|RB":"Alexander Mattison","MIN|20s|K":"Greg Joseph","MIN|20s|EDGE":"Danielle Hunter","MIN|20s|LB":"Jordan Hicks","MIN|20s|DB":"Byron Murphy Jr.",
# NE
"NE|60s|QB":"Babe Parilli","NE|60s|RB":"Jim Nance","NE|60s|WR":"Gino Cappelletti","NE|60s|EDGE":"Bob Dee","NE|60s|DB":"Ron Hall",
"NE|80s|QB":"Steve Grogan","NE|80s|WR":"Stanley Morgan",
"NE|90s|WR":"Ben Coates","NE|90s|K":"Matt Bahr","NE|90s|EDGE":"Willie McGinest","NE|90s|LB":"Chris Slade",
"NE|00s|LB":"Tedy Bruschi",
"NE|10s|RB":"Dion Lewis","NE|10s|EDGE":"Chandler Jones",
"NE|20s|QB":"Mac Jones","NE|20s|WR":"Jakobi Meyers","NE|20s|LB":"Ja'Whaun Bentley","NE|20s|DB":"J.C. Jackson",
# NO
"NO|70s|WR":"Danny Abramowicz","NO|70s|LB":"Joe Federspiel","NO|70s|DB":"Tommy Myers",
"NO|80s|RB":"Rueben Mayes","NO|80s|WR":"Eric Martin","NO|80s|DB":"Dave Waymer",
"NO|90s|RB":"Mario Bates","NO|90s|WR":"Quinn Early","NO|90s|DB":"Tyrone Hughes",
"NO|00s|K":"John Carney","NO|00s|EDGE":"Will Smith","NO|00s|LB":"Jonathan Vilma","NO|00s|DB":"Mike McKenzie",
"NO|10s|RB":"Mark Ingram","NO|10s|DB":"Marshon Lattimore",
"NO|20s|QB":"Derek Carr",
# NYG
"NYG|60s|K":"Don Chandler","NYG|60s|EDGE":"Andy Robustelli",
"NYG|70s|QB":"Craig Morton","NYG|70s|RB":"Ron Johnson","NYG|70s|WR":"Bob Tucker","NYG|70s|K":"Pete Gogolak","NYG|70s|EDGE":"Jack Gregory","NYG|70s|DB":"Spider Lockhart",
"NYG|80s|RB":"Joe Morris",
"NYG|90s|QB":"Dave Brown","NYG|90s|RB":"Rodney Hampton","NYG|90s|WR":"Chris Calloway","NYG|90s|K":"Brad Daluiso","NYG|90s|EDGE":"Michael Strahan","NYG|90s|LB":"Jessie Armstead",
"NYG|00s|QB":"Eli Manning","NYG|00s|WR":"Amani Toomer","NYG|00s|LB":"Antonio Pierce",
"NYG|10s|RB":"Rashad Jennings","NYG|10s|K":"Josh Brown","NYG|10s|EDGE":"Jason Pierre-Paul","NYG|10s|LB":"Devon Kennard","NYG|10s|DB":"Landon Collins",
"NYG|20s|QB":"Daniel Jones","NYG|20s|WR":"Darius Slayton","NYG|20s|LB":"Bobby Okereke",
# NYJ
"NYJ|60s|K":"Jim Turner","NYJ|60s|EDGE":"Gerry Philbin","NYJ|60s|DB":"Johnny Sample",
"NYJ|70s|QB":"Richard Todd","NYJ|70s|RB":"John Riggins","NYJ|70s|WR":"Rich Caster","NYJ|70s|EDGE":"Mark Gastineau","NYJ|70s|LB":"Greg Buttle","NYJ|70s|DB":"Burgess Owens",
"NYJ|80s|WR":"Al Toon","NYJ|80s|LB":"Lance Mehl","NYJ|80s|DB":"Kerry Glenn",
"NYJ|90s|QB":"Boomer Esiason","NYJ|90s|RB":"Adrian Murrell","NYJ|90s|K":"Nick Lowery","NYJ|90s|LB":"Mo Lewis","NYJ|90s|DB":"Aaron Glenn",
"NYJ|00s|QB":"Chad Pennington","NYJ|00s|DB":"Ty Law",
"NYJ|10s|QB":"Ryan Fitzpatrick","NYJ|10s|RB":"Matt Forte","NYJ|10s|WR":"Brandon Marshall","NYJ|10s|K":"Nick Folk","NYJ|10s|LB":"David Harris",
"NYJ|20s|QB":"Zach Wilson","NYJ|20s|K":"Greg Zuerlein",
# PHI
"PHI|60s|QB":"Norm Snead","PHI|60s|RB":"Timmy Brown","PHI|60s|K":"Sam Baker","PHI|60s|DB":"Irv Cross",
"PHI|70s|QB":"Ron Jaworski","PHI|70s|RB":"Wilbert Montgomery","PHI|70s|WR":"Harold Carmichael","PHI|70s|K":"Tom Dempsey","PHI|70s|EDGE":"Carl Hairston","PHI|70s|DB":"Herman Edwards",
"PHI|80s|RB":"Earnest Jackson","PHI|80s|LB":"Seth Joyner","PHI|80s|DB":"Wes Hopkins",
"PHI|90s|RB":"Ricky Watters","PHI|90s|WR":"Irving Fryar","PHI|90s|K":"Chris Boniol",
"PHI|00s|RB":"Brian Westbrook","PHI|00s|EDGE":"Jevon Kearse",
"PHI|10s|LB":"Nigel Bradham","PHI|10s|DB":"Malcolm Jenkins",
"PHI|20s|LB":"Haason Reddick",
# PIT
"PIT|80s|QB":"Mark Malone","PIT|80s|RB":"Frank Pollard","PIT|80s|EDGE":"Keith Gary",
"PIT|90s|WR":"Yancey Thigpen",
"PIT|00s|RB":"Willie Parker","PIT|00s|K":"Jeff Reed","PIT|00s|LB":"James Farrior",
"PIT|10s|EDGE":"Bud Dupree","PIT|10s|DB":"Joe Haden",
"PIT|20s|QB":"Kenny Pickett","PIT|20s|LB":"Elandon Roberts",
# SF
"SF|80s|K":"Ray Wersching","SF|80s|LB":"Keena Turner",
"SF|90s|RB":"Ricky Watters","SF|90s|LB":"Ken Norton Jr.","SF|90s|DB":"Merton Hanks",
"SF|00s|QB":"Jeff Garcia","SF|00s|LB":"Julian Peterson","SF|00s|DB":"Ahmed Plummer",
"SF|10s|RB":"Carlos Hyde","SF|10s|WR":"Anquan Boldin","SF|10s|DB":"Jimmie Ward",
"SF|20s|K":"Jake Moody","SF|20s|DB":"Charvarius Ward",
# SEA
"SEA|80s|QB":"Dave Krieg","SEA|80s|EDGE":"Jacob Green",
"SEA|90s|WR":"Brian Blades","SEA|90s|K":"Norm Johnson","SEA|90s|LB":"Terry Wooden","SEA|90s|DB":"Eugene Robinson",
"SEA|00s|WR":"Darrell Jackson","SEA|00s|EDGE":"Patrick Kerney","SEA|00s|DB":"Marcus Trufant",
"SEA|10s|WR":"Doug Baldwin","SEA|20s|EDGE":"Uchenna Nwosu",
# TB
"TB|80s|WR":"Kevin House","TB|80s|LB":"Hugh Green","TB|80s|DB":"Cedric Brown",
"TB|90s|QB":"Trent Dilfer","TB|90s|RB":"Warrick Dunn","TB|90s|WR":"Jacquez Green","TB|90s|EDGE":"Warren Sapp","TB|90s|DB":"John Lynch",
"TB|00s|QB":"Brad Johnson","TB|00s|WR":"Keyshawn Johnson",
"TB|10s|QB":"Jameis Winston","TB|10s|RB":"Doug Martin","TB|10s|DB":"Brent Grimes",
# TEN
"TEN|70s|QB":"Dan Pastorini","TEN|70s|RB":"Don Hardeman","TEN|70s|WR":"Ken Burrough","TEN|70s|K":"Skip Butler","TEN|70s|EDGE":"Elvin Bethea","TEN|70s|DB":"Mike Reinfeldt",
"TEN|80s|WR":"Drew Hill","TEN|80s|K":"Tony Zendejas","TEN|80s|EDGE":"William Fuller","TEN|80s|DB":"Vernon Perry",
"TEN|90s|WR":"Chris Sanders","TEN|90s|EDGE":"Kenny Holmes","TEN|90s|LB":"Eddie Robinson","TEN|90s|DB":"Blaine Bishop",
"TEN|00s|WR":"Drew Bennett","TEN|00s|LB":"Keith Bulluck","TEN|00s|DB":"Samari Rolle",
"TEN|10s|RB":"DeMarco Murray","TEN|10s|WR":"Rishard Matthews","TEN|10s|K":"Ryan Succop","TEN|10s|LB":"Wesley Woodyard",
"TEN|20s|K":"Nick Folk","TEN|20s|LB":"Harold Landry","TEN|20s|DB":"Kevin Byard",
# WAS
"WAS|60s|RB":"Bobby Mitchell","WAS|60s|K":"Charlie Gogolak","WAS|60s|LB":"Chris Hanburger","WAS|60s|DB":"Brig Owens",
"WAS|70s|QB":"Billy Kilmer","WAS|70s|K":"Mark Moseley","WAS|70s|DB":"Pat Fischer",
"WAS|80s|EDGE":"Dexter Manley","WAS|80s|LB":"Neal Olkewicz",
"WAS|90s|QB":"Gus Frerotte","WAS|90s|WR":"Michael Westbrook","WAS|90s|K":"Chip Lohmiller",
"WAS|00s|QB":"Patrick Ramsey","WAS|00s|K":"John Hall","WAS|00s|EDGE":"Phillip Daniels",
"WAS|10s|QB":"Kirk Cousins","WAS|10s|RB":"Alfred Morris","WAS|10s|DB":"Josh Norman",
"WAS|20s|RB":"Brian Robinson Jr.","WAS|20s|LB":"Jamin Davis","WAS|20s|DB":"Emmanuel Forbes",
}

# Stats templates by position (role-player level)
def make_stats(pos, decade):
    era_mult = {"60s":0.82,"70s":0.88,"80s":0.92,"90s":0.96,"00s":1.0,"10s":1.04,"20s":1.06}.get(decade, 1.0)
    if pos == "QB":
        return {"yds":int(2800*era_mult),"td":int(16*era_mult),"int":14,"rtg":round(76*era_mult,1)}
    elif pos == "RB":
        return {"yds":int(900*era_mult),"td":int(7*era_mult),"ypc":4.0,"rec":int(25*era_mult)}
    elif pos == "WR":
        return {"rec":int(55*era_mult),"yds":int(820*era_mult),"td":int(5*era_mult),"ypr":round(14.2,1)}
    elif pos == "K":
        return {"fgm":int(22*era_mult),"pct":round(76*era_mult,1),"lng":48,"pts":int(95*era_mult)}
    elif pos == "EDGE":
        return {"sck":round(7*era_mult,1),"tfl":int(11*era_mult),"ff":2,"tkl":int(55*era_mult)}
    elif pos == "LB":
        return {"tkl":int(95*era_mult),"sck":3,"int":2,"ff":2}
    elif pos == "DB":
        return {"int":3,"pd":int(10*era_mult),"tkl":int(55*era_mult),"ff":1}

# OVR by position (role players 74-82)
def make_ovr(pos, name):
    h = int(hashlib.md5(name.encode()).hexdigest()[:4], 16)
    return 74 + (h % 9)  # 74-82

lines = []
lines.append("  // ========== GAP FILLS (auto-generated) ==========")
for gap in GAPS:
    team, decade, pos = gap.split("|")
    name = KNOWN.get(gap)
    if not name:
        name = f"Player {gap}"
    ovr = make_ovr(pos, name)
    stats = make_stats(pos, decade)
    stats_str = json.dumps(stats).replace('"', '')
    # Convert stats keys to unquoted JS
    stats_js = "{" + ",".join(f"{k}:{v}" for k,v in stats.items()) + "}"
    lines.append(f'  {{name:"{name}",team:"{team}",decade:"{decade}",pos:"{pos}",stats:{stats_js},ovr:{ovr}}},')

print("\n".join(lines))
